trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: self
  fetchDepth: 0

# Prepare SonarCloud
- task: SonarCloudPrepare@3
  inputs:
    SonarCloud: 'SonarConnection'
    organization: 'c22770139'
    scannerMode: 'cli'
    configMode: 'manual'
    cliProjectKey: 'C22770139_calculator-sonarcloud-demo'
    cliProjectName: 'calculator-sonarcloud-demo'
    cliSources: 'src/main/java'
    extraProperties: |
      sonar.java.binaries=build/classes/java/main
      sonar.java.test.binaries=build/classes/java/test
      sonar.java.test.libraries=build/libs

# Build + test + coverage
- task: Gradle@3
  inputs:
    workingDirectory: ''
    gradleWrapperFile: 'gradlew'
    gradleOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '21'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/TEST-*.xml'
    tasks: 'clean build test jacocoTestReport'

# Publish coverage (optional but required by your lab)
- task: PublishCodeCoverageResults@2
  inputs:
    summaryFileLocation: '$(System.DefaultWorkingDirectory)/**/build/reports/jacoco/test/jacocoTestReport.xml'
    pathToSources: '$(System.DefaultWorkingDirectory)/src/main/java/'

# Run SonarCloud analysis
- task: SonarCloudAnalyze@3

# Publish analysis
- task: SonarCloudPublish@3
  inputs:
    pollingTimeoutSec: '300'