trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: self
  fetchDepth: 0

# Prepare SonarCloud using GRADLE scanner
- task: SonarCloudPrepare@3
  inputs:
    SonarCloud: 'SonarConnection'
    organization: 'C22770139'
    scannerMode: 'Other'         
    configMode: 'manual'          
    extraProperties: |
      sonar.projectKey=C22770139_calculator-sonarcloud-demo
      sonar.projectName=calculator-sonarcloud-demo
      sonar.gradle.skipCompile=true

# Build + test + coverage (NO sonar here)
- task: Gradle@3
  inputs:
    gradleWrapperFile: 'gradlew'
    publishJUnitResults: true
    testResultsFiles: '**/TEST-*.xml'
    tasks: 'clean build test jacocoTestReport sonar'

# Publish coverage to Azure DevOps
- task: PublishCodeCoverageResults@2
  inputs:
    summaryFileLocation: '$(System.DefaultWorkingDirectory)/**/build/reports/jacoco/test/jacocoTestReport.xml'
    pathToSources: '$(System.DefaultWorkingDirectory)/src/main/java/'

# Finalize SonarCloud analysis
- task: SonarCloudPublish@3
  inputs:
    pollingTimeoutSec: '300'
